# Generated by Django 4.1.3 on 2022-11-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generaluser',
            fields=[
                ('general_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('is_alive', models.BooleanField()),
                ('is_author', models.BooleanField()),
            ],
            options={
                'db_table': 'generaluser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'journal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.journal')),
            ],
            options={
                'db_table': 'publication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.generaluser')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.publication')),
            ],
            options={
                'db_table': 'writes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.generaluser')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.institution')),
            ],
            options={
                'db_table': 'belongs',
                'managed': True,
            },
        ),
    ]
