# Generated by Django 4.1.3 on 2022-12-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citations',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citations',
            name='citee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='citee', to='scinet_app.publication'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='citations',
            unique_together={('citer', 'citee')},
        ),
    ]
