# Generated by Django 4.1.3 on 2022-12-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scinet_app.publication')),
            ],
            options={
                'db_table': 'quotes',
                'managed': True,
            },
        ),
    ]
