# Generated by Django 4.1.3 on 2022-12-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='citations',
            field=models.ManyToManyField(to='scinet_app.citation'),
        ),
    ]
