# Generated by Django 4.1.3 on 2022-12-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0002_alter_publication_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='citations',
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
