# Generated by Django 4.1.3 on 2022-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0003_remove_publication_citations_delete_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='general_user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
