# Generated by Django 4.1.3 on 2022-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0003_rename_general_user_belongs_general_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
