# Generated by Django 4.1.3 on 2022-12-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0004_citations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citations',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citations',
            name='cited',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cited', to='scinet_app.publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='general_user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='citations',
            unique_together={('citer', 'cited')},
        ),
        migrations.RemoveField(
            model_name='citations',
            name='citee',
        ),
    ]
