# Generated by Django 4.1.3 on 2022-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scinet_app', '0004_alter_generaluser_general_user_id_and_more'),
        ('scinet_app', '0004_citations'),
    ]

    operations = [
    ]
