version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/ver/lib/posgres/data
    environment:
      - POSTGRES_DB=scinet
      - POSTGRES_USER=scinet
      - POSTGRES_PASSWORD=wendy02
  web:
    restart: always
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000 
                      && pythom manage.py populate"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

